### ISSUE TITLE
Bug:  listViewVC.navigationItem.title = nil

### ISSUE THREAD

**Issue by kristoff2016** [SwiftTsubame/ViperMovieApp#1]
Hello Thanks for sharing your app.
I tried to set title = nil I have to display "< back " instead but it is not working

thanks

**Comment by SwiftTsubame** [comment]
You can do it to set any text before "< back "

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        title = "Movies"
        presenter?.loadMovies()
    }` 

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        title = " " // You can set it to be "Back" as well 
    }`

**Comment by SwiftTsubame** [comment]
Could I close this? Hope it helps :D

**Comment by kristoff2016** [comment]
@SwiftTsubame thanks for your replied
